// @license@ 
package nanosome.fit {
	
	/**
	 * Version of the nanosome-bind project.
	 * 
	 * <p>This version is automatically generated by the build process.</p>
	 * 
	 * @author Martin Heidegger mh@leichtgewicht.at
	 */
	public const version: String = "@version@";
}
